### ISSUE TITLE
Generate cache as lua bytecode

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#131]
### Issue/Question/Enhancement

Both [catppuccin](https://github.com/catppuccin/catppuccin) and [nightfox](https://github.com/EdenEast/nightfox.nvim) have launched some pretty cool lua bytecode compilation in recent days. Testing with nightfox, with no additional configuration, I'm seeing load times of `0.54ms` versus `0.95ms` with OneDarkPro. Not quite a like-for-like as I left filetype highlights in but a sign that more can be done!

---

For this enhancement, I propose the ability of the colorscheme to write to the cache file as lua bytecode for improved loading times. Combined with #130, this should lead to substantially improved performance for most users.

I also think this may necessitate the removal of the `caching` config option as it should be on by default.

**Comment by mmirus** [comment]
:wave: this sounds great, but would it be possible to keep an option to disable caching (even if it becomes opt-out, rather than opt-in)?

I haven't been able to keep caching enabled, as each time I've tried it out it causes something I value more to stop working. The last thing that made me disable it, I believe, was issues with the styles for the QF window when `window_unfocused_color` is enabled.

Of course it's possible that this update to the caching mechanism could resolve issues like that, and then it would be moot.

**Comment by olimorris** [comment]
That's really odd and I'll make sure that nothing gets merged into main until we can guarantee that everything works as intended.

I too stopped using it but mainly because the overhead of making a change to my setup and remembering to re-cache was too great but I didn't notice any performance issues or experience any drop in functionality. Unlike nightfox, it uses pretty much the same methods to apply highlights as it does to write to the cache file.

When loading from the cache, I'm not sure the autocmds relating to `window_unfocused_color` every got applied...
