### ISSUE TITLE
Indent blankline is not colored

### ISSUE THREAD

**Issue by erancx** [olimorris/onedarkpro.nvim#18]
Hey,

First, I'd like to say I really love Onedarkpro theme! I think this turns to be my favorite!

It seems like indent blankline is not colored when you [hover](https://user-images.githubusercontent.com/12900252/140518531-522aa67a-b377-498c-ad39-85113b2b56df.png) on it.
Also, YAML keys are not highlighted (is this expected behavior?)

Last but not least, can this be supported with base16?

Thank you for this!

**Comment by olimorris** [comment]
So glad you're enjoying it!

> It seems like indent blankline is not colored when you hover on it.

So I've tried to get this to work in my own config. I can't seem to at all. Can you share yours? Also, you can override/create `hlgroups` with the [theme](https://github.com/olimorris/onedarkpro.nvim#configuring-highlight-groups). I have a tonne in my own dotfiles.

> Also, YAML keys are not highlighted (is this expected behavior?)

Ah yes. I've been waiting for someone to bring this up. In order to closely match the VS Code version of One Dark Pro I had to make some compromises in the theme regarding `treesitter` hlgroups. One of them massively affected how a `yaml` file looks. The exact one I can't remember now. I wonder if I can fix this with a `FileType` auto command... 🤔 . Leave it with me.

> Last but not least, can this be supported with base16?

Hmmmm. Not sure how I do this. I have defined the base colors [here](https://github.com/olimorris/onedarkpro.nvim/blob/fd4dd7a09bac975c94612ce3c8fa98a51bcce412/lua/onedarkpro/utils.lua#L180) and you can technically call them with the (undocumented) `terminal_colors` option in the config. Can you let me know how other theme's do this or what settlings you apply to achieve this? Is `termguicolors` off?

**Comment by olimorris** [comment]
> It seems like indent blankline is not colored when you hover on it.

Try the latest commit now.

**Comment by erancx** [comment]
I just updated to latest version, still not working.
My config can be found [here](https://github.com/erancx/dotfiles/blob/main/.config/nvim/lua/general/settings.lua#L5) (just copied it over from your config.

YAML is nice to have feature but obviously not urgent at all :)

I'll look at https://github.com/RRethy/nvim-base16 and add `Onedarkpro` to that repository.

Again, amazing work dude!

**Comment by erancx** [comment]
I enabled `show_first_indent_level` on indent line and I can see the first line is a static purple color but if you hoover to other levels it won't color it

**Comment by olimorris** [comment]
> I enabled `show_first_indent_level` on indent line and I can see the first line is a static purple color but if you hoover to other levels it won't color it

Hmmm. By enabling `show_current_context` and `show_current_context_start`, this is what I get:

![Screen Shot 2021-11-25 at 18 17 41](https://user-images.githubusercontent.com/9512444/143487285-d28b8f9c-10a6-4eeb-a250-ff7760669f70.gif)

Perhaps I'm misunderstanding. What about if you overwrite the hlgroups for the plugin?

**Comment by olimorris** [comment]
> YAML is nice to have feature but obviously not urgent at all :)

It has bothered me for some time. I'm going to open it as it's own issue and see if I can resolve it at a later point in time

**Comment by erancx** [comment]
I have both `show_current_context` and `show_current_context_start` and still only the first level is being colored.
What should I set with `hlgroups`?

What version of Neovim do you use?

**Comment by olimorris** [comment]
Weird. I am using `0.5.1`. Do you have `use_treesitter` enabled too?

**Comment by erancx** [comment]
yeah, I have `use_treesitter` enabled [here](https://github.com/erancx/dotfiles/blob/main/.config/nvim/lua/plugins/indent_blank_line.lua#L3).

is there any way to increase debug mode to view some additional settings?

**Comment by erancx** [comment]
Here's an example

[![asciicast](https://asciinema.org/a/kKaZMNR1nrKW09LoDV1nU2pM3.svg)](https://asciinema.org/a/kKaZMNR1nrKW09LoDV1nU2pM3)

**Comment by erancx** [comment]
I just changed colorscheme and I'm still having the same behavior.

Let me debug that and report back here

**Comment by olimorris** [comment]
> I just changed colorscheme and I'm still having the same behavior.
> 

Bizzarely, I deleted the plugin and reinstalled it. No idea why that worked I don't believe it caches anything, but it did solve it.
