### ISSUE TITLE
Add filetype specific highlight groups

### ISSUE THREAD

**Issue by olimorris** [olimorris/onedarkpro.nvim#27]
Currently working on a [feature](https://github.com/olimorris/onedarkpro.nvim/tree/feature/filetype-hlgroups) to enable custom highlight groups by filetype.

**Comment by olimorris** [comment]
@mmirus I've fixed the two issues you spotted in the latest commit. Please let me know what you think.

The solution to the floating windows was to ignore specific filetypes and buffer types.

**Comment by mmirus** [comment]
Thanks for the fixes! I've confirmed that I can't reproduce those bugs anymore.

Here's what I'm seeing now, using the same test config as before:

```yaml
  hlgroups = {
    TSFunction = {fg = "${orange}"},
  },
  filetype_hlgroups = {
    yaml = {
      TSField = { fg = "${red}" },
    },
    javascript = {
      TSFunction = { fg = "${green}" },
    },
    php = {
      TSFunction = { fg = "${purple}" },
    },
    ruby = {
      TSFunction = { fg = "${blue}" },
    }
  },
```

First, syntax highlighting in Telescope's preview uses the highlight groups of the filetype in the buffer that was open when Telescope was called rather than the filetype of the file being previewed.

For example:
- Given a JavaScript hlgroup that sets the TSFunction fg to green
- And a Ruby hlgroup that sets the TSFunction fg to red
- When I open a JS file
- And then I open the Telescope file finder and preview a Ruby file
- The function names in the preview window should be red, but are actually green

Second, if I switch to a buffer that uses the non-file-type-specific hl group (the orange one, above), and then back to one that matches a rule for a specific file type (e.g., PHP), the PHP file will use the generic color instead of the PHP color. If I then switch to a file that has a specific rule (e.g., JS) and back to PHP, the correct colors are shown.

Demo:
![filetype highlight group bug-2022-02-11_14 49 36-optimized](https://user-images.githubusercontent.com/524994/153659978-54e0ea5e-094e-4fdf-995f-1d3a8083c8f6.gif)

**Comment by olimorris** [comment]
That is some epic testing! Thanks so much. I shall see if I can resolve!

**Comment by mmirus** [comment]
You got it!

**Comment by olimorris** [comment]
Struggling to solve the `Telescope` previewer issues. Will open an issue on their side and ask for help. Seems Telescope reads the file asynchronously with `vim.loop.fs_` and there is no way to detect when you preview a `ruby` then a `js` file.

Key question: how much of a nuisance would it be for you?
